import test from 'node:test';
import assert from 'node:assert/strict';
import { createShell, execute, complete, HOME } from '../src/lib/terminal.mjs';
const make=()=>createShell({about:['Existing biography.'],languages:['C'],projects:[{title:'Existing Project',dis:'Real description',tags:['React'],link:'https://example.com'}]});
test('filesystem navigation and file content remain internally consistent',()=>{const s=make();assert.match(execute(s,'ls').text,/projects\//);execute(s,'cd projects');assert.equal(execute(s,'pwd').text,HOME+'/projects');assert.match(execute(s,'cat existing-project.txt').text,/Real description/);execute(s,'cd ..');assert.match(execute(s,'cat resume.txt').text,/Existing biography/);assert.match(execute(s,'cd resume.txt').text,/Not a directory/);assert.equal(s.cwd,HOME);});
test('text tools, paging and errors',()=>{const s=make();s.fs[HOME+'/sample.txt']='one\ntwo\nthree';assert.equal(execute(s,'head -n 2 sample.txt').text,'one\ntwo');assert.equal(execute(s,'tail -n 1 sample.txt').text,'three');assert.equal(execute(s,'tail -n 0 sample.txt').text,'');assert.equal(execute(s,'grep -i TWO sample.txt').text,'two');assert.equal(execute(s,'less sample.txt').pager,true);assert.match(execute(s,'cat missing').text,/No such file/);assert.match(execute(s,'head -n -1 sample.txt').text,/invalid/);assert.match(execute(s,'badcmd').text,/command not found/);});
test('mkdir, tree, find and path autocomplete',()=>{const s=make();execute(s,'mkdir -p notes/ideas');assert.match(execute(s,'tree notes').text,/ideas/);assert.match(execute(s,'find . -name *.txt').text,/resume.txt/);assert.equal(complete(s,'cat res').line,'cat resume.txt ');assert.equal(complete(s,'cd pro').line,'cd projects/');assert.equal(complete(s,'./sna').line,'./snake.exe ');execute(s,'cd notes');assert.equal(execute(s,'pwd').text,HOME+'/notes');execute(s,'cd -');assert.equal(s.cwd,HOME);});
test('executables require existing paths and emit explicit world actions',()=>{const s=make();assert.equal(execute(s,'./explode.exe').action,'explode');assert.equal(execute(s,'./oldsite.exe').action,'oldsite');assert.match(execute(s,'ls').text,/oldsite\.exe/);execute(s,'cd projects');assert.match(execute(s,'./explode.exe').text,/No such executable/);assert.equal(execute(s,'../coffee.exe').action,'coffee');assert.equal(execute(s,'reset').action,'reset');assert.deepEqual(execute(s,'music volume 50').args,['volume','50']);assert.equal(execute(s,'exit').action,'exit');});
test('quotes, history, simulated boundaries and no real shell execution',()=>{const s=make();assert.equal(execute(s,'echo "hello world"').text,'hello world');assert.match(execute(s,'echo "oops').text,/unclosed quote/);assert.match(execute(s,'history').text,/hello world/);assert.equal(execute(s,'echo $(rm -rf /)').action,null);execute(s,'cd /');execute(s,'cd ../../');assert.equal(s.cwd,'/');assert.match(execute(s,'cat /etc/passwd').text,/No such file/);});
